server:
  port: 8080

spring:
  application:
    name: auth
 
  datasource:
    url: jdbc:postgresql://localhost:5432/dineflow
    username: postgres
    password: 0768847208

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:change-this-to-a-long-secret-key-at-least-32-characters}
  expiration: 86400000